const tilesData = [
  {
    id: 0,
    name: "Start.",
    type: "start",
    img: "",
    owner: "",
    lv: 0,
    price: 0,
    resale: 0,
    rent: [0, 0, 0, 0],
    upgrade: 0,
  },
  {
    id: 1,
    name: "Mushroom Road.",
    type: "normal",
    img: "https://i.pinimg.com/originals/50/b6/36/50b636f399c41e8697972676ebe85dff.jpg",
    owner: "",
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "2",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: "",
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: 3,
    name: "test temple.",
    type: "spacial",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 0,
  },
  {
    id: 4,
    name: "test tile.",
    type: "normal",
    img: "",
    owner: "",
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: "",
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
  {
    id: "test",
    name: "test tile.",
    type: "normal",
    img: "",
    owner: 0,
    lv: 0,
    price: 60,
    resale: 120,
    rent: [2, 10, 90, 250],
    upgrade: 50,
  },
];
